### PR TITLE
Week3

### PR DESCRIPTION
**Pull request by mortonjt**
Got the notes for Fridays meeting.  @ElDeveloper, what do you think?

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Looks good.

**Comment by anupriyatripathi** [comment]
Looks great, thanks a lot for putting this together.

Anupriya Tripathi

On 12 October 2016 at 09:05, Yoshiki Vázquez Baeza <notifications@github.com

**Comment by ElDeveloper** [comment]
If someone who has merge-permissions can merge this, that would be wonderful.

**Comment by ElDeveloper** [comment]
Thanks @antgonza!

**Pull request merged**
